name: 'Anchor Build Container'
description: 'A container for building Anchor programs.'

branding:
  icon: anchor
  color: blue

inputs:
  run:
    description: 'The command(s) to run.'
    default: 'anchor build'
  solana-cluster:
    description: 'The cluster to use for the solana sdk.'
    required: false
    default: 'devnet'
  solana-key:
    description: 'The private key to use for the solana sdk.'
    required: false
  anchor-version:
    description: 'The version of anchor to use.'
    default: 'latest'

runs:
  using: "docker"
  image: "ghcr.io/wjthieme/anchor-build:${{ inputs.anchor-version }}"
  args:
    - ${{ inputs.run }}
    - ${{ inputs.solana-cluster }}
    - ${{ inputs.solana-key }}
